---
version: '3.3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.2
    cap_add:
      - IPC_LOCK
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    environment:
      - discovery.type:single-node
    ports:
      - 9200:9200
  backend:
    build: backend
    environment:
        - EU_LUMINIS_ELASTIC_HOSTNAMES=elasticsearch:9200
    ports:
      - 8080:8080
volumes:
  esdata1:
    driver: local